module.exports = {
    getConversations: 'GET_CONVERSATIONS',
    getSearchResults: 'GET_SEARCH_RESULTS',
    fileUpload: 'FILE_UPLOAD',
    register: 'REGISTER',
    getRegisterId: 'GET_REGISTER_ID',
    userList: 'USER_LIST',
    addUser: 'ADD_USER',
    getChatId: 'GET_CHAT_ID',
    chatDetails: 'CHAT_DETAILS',
    selectedChat: 'SELECTED_CHAT',
    newMessage: 'NEW_MESSAGE',
    getMessages: 'GET_MESSAGES',
    clearMessages: 'CLEAR_MESSAGES',
};
